export const ProductService = {
    getProductsData() {
        return [
            {
                id: "1000",
                code: "f230fh0g3",
                name: "Rejoice",
                description: "Product Description",
                image: "bamboo-watch.jpg",
                price: 16,
                category: "Accessories",
                quantity: 24,
                inventoryStatus: "INSTOCK",
                rating: 5,
            },
            {
                id: "1001",
                code: "nvklal433",
                name: "Soap",
                description: "Product Description",
                image: "black-watch.jpg",
                price: 17,
                category: "Accessories",
                quantity: 61,
                inventoryStatus: "INSTOCK",
                rating: 4,
            },
            {
                id: "1002",
                code: "zz21cz3c1",
                name: "Soap",
                description: "Product Description",
                image: "blue-band.jpg",
                price: 79,
                category: "Fitness",
                quantity: 2,
                inventoryStatus: "LOWSTOCK",
                rating: 3,
            },
            {
                id: "1003",
                code: "244wgerg2",
                name: "Cup Noodles",
                description: "Product Description",
                image: "blue-t-shirt.jpg",
                price: 29,
                category: "Clothing",
                quantity: 25,
                inventoryStatus: "INSTOCK",
                rating: 5,
            },
            {
                id: "1004",
                code: "h456wer53",
                name: "Mineral Water",
                description: "Product Description",
                image: "bracelet.jpg",
                price: 15,
                category: "Accessories",
                quantity: 73,
                inventoryStatus: "INSTOCK",
                rating: 4,
            },
            {
                id: "1005",
                code: "av2231fwg",
                name: "Chippy",
                description: "Product Description",
                image: "brown-purse.jpg",
                price: 120,
                category: "Accessories",
                quantity: 0,
                inventoryStatus: "OUTOFSTOCK",
                rating: 4,
            },
            {
                id: "1006",
                code: "bib36pfvm",
                name: "Oishi",
                description: "Product Description",
                image: "chakra-bracelet.jpg",
                price: 32,
                category: "Accessories",
                quantity: 5,
                inventoryStatus: "LOWSTOCK",
                rating: 3,
            },
            {
                id: "1007",
                code: "mbvjkgip5",
                name: "",
                description: "Product Description",
                image: "galaxy-earrings.jpg",
                price: 34,
                category: "Accessories",
                quantity: 23,
                inventoryStatus: "INSTOCK",
                rating: 5,
            },
            {
                id: "1008",
                code: "vbb124btr",
                name: "Game Controller",
                description: "Product Description",
                image: "game-controller.jpg",
                price: 99,
                category: "Electronics",
                quantity: 2,
                inventoryStatus: "LOWSTOCK",
                rating: 4,
            },
            {
                id: "1009",
                code: "cm230f032",
                name: "Gaming Set",
                description: "Product Description",
                image: "gaming-set.jpg",
                price: 299,
                category: "Electronics",
                quantity: 63,
                inventoryStatus: "INSTOCK",
                rating: 3,
            },
            {
                id: "1010",
                code: "plb34234v",
                name: "Gold Phone Case",
                description: "Product Description",
                image: "gold-phone-case.jpg",
                price: 24,
                category: "Accessories",
                quantity: 0,
                inventoryStatus: "OUTOFSTOCK",
                rating: 4,
            },
            {
                id: "1011",
                code: "4920nnc2d",
                name: "Green Earbuds",
                description: "Product Description",
                image: "green-earbuds.jpg",
                price: 89,
                category: "Electronics",
                quantity: 23,
                inventoryStatus: "INSTOCK",
                rating: 4,
            },
            {
                id: "1012",
                code: "250vm23cc",
                name: "Green T-Shirt",
                description: "Product Description",
                image: "green-t-shirt.jpg",
                price: 49,
                category: "Clothing",
                quantity: 74,
                inventoryStatus: "INSTOCK",
                rating: 5,
            },
            {
                id: "1013",
                code: "fldsmn31b",
                name: "Grey T-Shirt",
                description: "Product Description",
                image: "grey-t-shirt.jpg",
                price: 48,
                category: "Clothing",
                quantity: 0,
                inventoryStatus: "OUTOFSTOCK",
                rating: 3,
            },
            {
                id: "1014",
                code: "waas1x2as",
                name: "Headphones",
                description: "Product Description",
                image: "headphones.jpg",
                price: 175,
                category: "Electronics",
                quantity: 8,
                inventoryStatus: "LOWSTOCK",
                rating: 5,
            },
            {
                id: "1015",
                code: "vb34btbg5",
                name: "Light Green T-Shirt",
                description: "Product Description",
                image: "light-green-t-shirt.jpg",
                price: 49,
                category: "Clothing",
                quantity: 34,
                inventoryStatus: "INSTOCK",
                rating: 4,
            },
            {
                id: "1016",
                code: "k8l6j58jl",
                name: "Lime Band",
                description: "Product Description",
                image: "lime-band.jpg",
                price: 79,
                category: "Fitness",
                quantity: 12,
                inventoryStatus: "INSTOCK",
                rating: 3,
            },
            {
                id: "1017",
                code: "v435nn85n",
                name: "Mini Speakers",
                description: "Product Description",
                image: "mini-speakers.jpg",
                price: 85,
                category: "Clothing",
                quantity: 42,
                inventoryStatus: "INSTOCK",
                rating: 4,
            },
            {
                id: "1018",
                code: "09zx9c0zc",
                name: "Painted Phone Case",
                description: "Product Description",
                image: "painted-phone-case.jpg",
                price: 56,
                category: "Accessories",
                quantity: 41,
                inventoryStatus: "INSTOCK",
                rating: 5,
            },
            {
                id: "1019",
                code: "mnb5mb2m5",
                name: "Pink Band",
                description: "Product Description",
                image: "pink-band.jpg",
                price: 79,
                category: "Fitness",
                quantity: 63,
                inventoryStatus: "INSTOCK",
                rating: 4,
            },
            {
                id: "1020",
                code: "r23fwf2w3",
                name: "Pink Purse",
                description: "Product Description",
                image: "pink-purse.jpg",
                price: 110,
                category: "Accessories",
                quantity: 0,
                inventoryStatus: "OUTOFSTOCK",
                rating: 4,
            },
            {
                id: "1021",
                code: "pxpzczo23",
                name: "Purple Band",
                description: "Product Description",
                image: "purple-band.jpg",
                price: 79,
                category: "Fitness",
                quantity: 6,
                inventoryStatus: "LOWSTOCK",
                rating: 3,
            },
            {
                id: "1022",
                code: "2c42cb5cb",
                name: "Purple Gemstone Necklace",
                description: "Product Description",
                image: "purple-gemstone-necklace.jpg",
                price: 45,
                category: "Accessories",
                quantity: 62,
                inventoryStatus: "INSTOCK",
                rating: 4,
            },
            {
                id: "1023",
                code: "5k43kkk23",
                name: "Purple T-Shirt",
                description: "Product Description",
                image: "purple-t-shirt.jpg",
                price: 49,
                category: "Clothing",
                quantity: 2,
                inventoryStatus: "LOWSTOCK",
                rating: 5,
            },
            {
                id: "1024",
                code: "lm2tny2k4",
                name: "Shoes",
                description: "Product Description",
                image: "shoes.jpg",
                price: 64,
                category: "Clothing",
                quantity: 0,
                inventoryStatus: "INSTOCK",
                rating: 4,
            },
            {
                id: "1025",
                code: "nbm5mv45n",
                name: "Sneakers",
                description: "Product Description",
                image: "sneakers.jpg",
                price: 78,
                category: "Clothing",
                quantity: 52,
                inventoryStatus: "INSTOCK",
                rating: 4,
            },
            {
                id: "1026",
                code: "zx23zc42c",
                name: "Teal T-Shirt",
                description: "Product Description",
                image: "teal-t-shirt.jpg",
                price: 49,
                category: "Clothing",
                quantity: 3,
                inventoryStatus: "LOWSTOCK",
                rating: 3,
            },
            {
                id: "1027",
                code: "acvx872gc",
                name: "Yellow Earbuds",
                description: "Product Description",
                image: "yellow-earbuds.jpg",
                price: 89,
                category: "Electronics",
                quantity: 35,
                inventoryStatus: "INSTOCK",
                rating: 3,
            },
            {
                id: "1028",
                code: "tx125ck42",
                name: "Yoga Mat",
                description: "Product Description",
                image: "yoga-mat.jpg",
                price: 20,
                category: "Fitness",
                quantity: 15,
                inventoryStatus: "INSTOCK",
                rating: 5,
            },
            {
                id: "1029",
                code: "gwuby345v",
                name: "Yoga Set",
                description: "Product Description",
                image: "yoga-set.jpg",
                price: 20,
                category: "Fitness",
                quantity: 25,
                inventoryStatus: "INSTOCK",
                rating: 8,
            },
        ];
    },

    getProductsWithOrdersData() {
        return [
            {
                id: 1,
                name: "Product A",
                brand: "Brand A",
                description: "Description A",
                category: "Non-Consumable",
                inventoryStatus: "INSTOCK",
                batches: [
                    {
                        batchId: 101,
                        batchNumber: "Batch A1",
                        quantity: 50,
                        purchaseDate: "2024-01-17",
                        purchasePrice: 458.02, // Rounded for clarity
                        unit: "Box",
                        supplier: "Supplier A",
                        rental: "yes",
                        rentalprice: 345.0,
                        warrantyValue: 1,
                        warrantyUnit: "year(s)",
                        minimumstocks: 12,
                        stocklimit: 100,
                        status: "Active",
                        serialNumbers: [
                            {
                                serialNumber: "SN11",
                                status: "Available",
                                rental: "No",
                                rentalPrice: "-",
                                roomNumber: "-",
                            },
                            {
                                serialNumber: "SN12",
                                status: "Assigned",
                                rental: "yes",
                                rentalPrice: "900",
                                roomNumber: "101",
                            },
                            {
                                serialNumber: "SN13",
                                status: "Assigned",
                                rental: "yes",
                                rentalPrice: "900",
                                roomNumber: "101",
                            },
                            {
                                serialNumber: "SN14",
                                status: "Available",
                                rental: "No",
                                rentalPrice: "-",
                                roomNumber: "-",
                            },
                        ],
                    },
                ],
            },
            {
                id: 2,
                name: "Product B",
                brand: "Brand B",
                description: "Description B",
                category: "Non-Consumable",
                inventoryStatus: "OUTOFSTOCK",
                batches: [
                    {
                        batchId: 201,
                        batchNumber: "Batch B2",
                        quantity: 97,
                        purchaseDate: "2024-05-15",
                        purchasePrice: 385.91711641568344,
                        unit: "L",
                        supplier: "Supplier B",
                        expDate: "2025-05-06",
                        status: "Inactive",
                        serialNumbers: [{ serialNumber: "SN21" }],
                    },
                ],
            },
            {
                id: 3,
                name: "Product C",
                brand: "Brand C",
                description: "Description C",
                category: "Non-Consumable",
                inventoryStatus: "INSTOCK",
                batches: [
                    {
                        batchId: 301,
                        batchNumber: "Batch C3",
                        quantity: 74,
                        purchaseDate: "2024-04-11",
                        purchasePrice: 353.4962782936761,
                        unit: "Kg",
                        supplier: "Supplier C",
                        expDate: "2025-07-04",
                        status: "Active",
                        serialNumbers: [
                            { serialNumber: "SN31" },
                            { serialNumber: "SN32" },
                        ],
                    },
                ],
            },
            {
                id: 4,
                name: "Product D",
                brand: "Brand D",
                description: "Description D",
                category: "Consumable",
                inventoryStatus: "INSTOCK",
                batches: [
                    {
                        batchId: 401,
                        batchNumber: "Batch D4",
                        quantity: 85,
                        purchaseDate: "2024-09-09",
                        purchasePrice: 65.75234191392829,
                        srp: 20,
                        unit: "L",
                        supplier: "Supplier D",
                        expDate: "2025-01-27",
                        status: "Active",
                        serialNumbers: [
                            { serialNumber: "SN41", srp: "90" },
                            { serialNumber: "SN42", srp: "50" },
                            { serialNumber: "SN43", srp: "60" },
                        ],
                    },
                ],
            },
            {
                id: 5,
                name: "Product E",
                brand: "Brand E",
                description: "Description E",
                category: "Consumable",
                inventoryStatus: "INSTOCK",
                batches: [
                    {
                        batchId: 501,
                        batchNumber: "Batch E5",
                        quantity: 12,
                        purchaseDate: "2024-10-06",
                        purchasePrice: 424.8145869198751,
                        unit: "Kg",
                        supplier: "Supplier E",
                        expDate: "2025-08-04",
                        status: "Active",
                        serialNumbers: [
                            { serialNumber: "SN51" },
                            { serialNumber: "SN52" },
                            { serialNumber: "SN53" },
                        ],
                    },
                ],
            },
            {
                id: 6,
                name: "Product F",
                brand: "Brand F",
                description: "Description F",
                category: "Consumable",
                inventoryStatus: "INSTOCK",
                batches: [
                    {
                        batchId: 601,
                        batchNumber: "Batch F6",
                        quantity: 94,
                        purchaseDate: "2024-01-18",
                        purchasePrice: 140.40566449483654,
                        unit: "pcs",
                        supplier: "Supplier F",
                        expDate: "2025-11-13",
                        status: "Active",
                        serialNumbers: [
                            { serialNumber: "SN61" },
                            { serialNumber: "SN62" },
                        ],
                    },
                ],
            },
            {
                id: 7,
                name: "Product G",
                brand: "Brand G",
                description: "Description G",
                category: "Consumable",
                inventoryStatus: "INSTOCK",
                batches: [
                    {
                        batchId: 701,
                        batchNumber: "Batch G7",
                        quantity: 39,
                        purchaseDate: "2024-02-01",
                        purchasePrice: 71.51085267608018,
                        unit: "pcs",
                        supplier: "Supplier G",
                        expDate: "2025-09-24",
                        status: "Inactive",
                        serialNumbers: [
                            { serialNumber: "SN71" },
                            { serialNumber: "SN72" },
                            { serialNumber: "SN73" },
                        ],
                    },
                ],
            },
            {
                id: 8,
                name: "Product H",
                brand: "Brand H",
                description: "Description H",
                category: "Consumable",
                inventoryStatus: "OUTOFSTOCK",
                batches: [
                    {
                        batchId: 801,
                        batchNumber: "Batch H8",
                        quantity: 15,
                        purchaseDate: "2024-09-17",
                        purchasePrice: 217.7491360184235,
                        unit: "pcs",
                        supplier: "Supplier H",
                        expDate: "2025-11-04",
                        status: "Inactive",
                        serialNumbers: [
                            { serialNumber: "SN81" },
                            { serialNumber: "SN82" },
                            { serialNumber: "SN83" },
                            { serialNumber: "SN84" },
                        ],
                    },
                ],
            },
            {
                id: 9,
                name: "Product I",
                brand: "Brand I",
                description: "Description I",
                category: "Consumable",
                inventoryStatus: "INSTOCK",
                batches: [
                    {
                        batchId: 901,
                        batchNumber: "Batch I9",
                        quantity: 41,
                        purchaseDate: "2024-07-13",
                        purchasePrice: 370.15726446508967,
                        unit: "Kg",
                        supplier: "Supplier I",
                        expDate: "2025-02-23",
                        status: "Inactive",
                        serialNumbers: [
                            { serialNumber: "SN91" },
                            { serialNumber: "SN92" },
                            { serialNumber: "SN93" },
                        ],
                    },
                ],
            },
            {
                id: 10,
                name: "Product J",
                brand: "Brand J",
                description: "Description J",
                category: "Consumable",
                inventoryStatus: "OUTOFSTOCK",
                batches: [
                    {
                        batchId: 1001,
                        batchNumber: "Batch J10",
                        quantity: 57,
                        purchaseDate: "2024-04-02",
                        purchasePrice: 171.51995118128735,
                        unit: "Kg",
                        supplier: "Supplier J",
                        expDate: "2025-05-22",
                        status: "Active",
                        serialNumbers: [{ serialNumber: "SN101" }],
                    },
                ],
            },
            {
                id: 11,
                name: "Product K",
                brand: "Brand K",
                description: "Description K",
                category: "Non-Consumable",
                inventoryStatus: "OUTOFSTOCK",
                batches: [
                    {
                        batchId: 1101,
                        batchNumber: "Batch K11",
                        quantity: 61,
                        purchaseDate: "2024-02-17",
                        purchasePrice: 309.440444148843,
                        unit: "Kg",
                        supplier: "Supplier K",
                        expDate: "2025-04-20",
                        status: "Active",
                        serialNumbers: [
                            { serialNumber: "SN111" },
                            { serialNumber: "SN112" },
                            { serialNumber: "SN113" },
                            { serialNumber: "SN114" },
                        ],
                    },
                ],
            },
            {
                id: 12,
                name: "Product L",
                brand: "Brand L",
                description: "Description L",
                category: "Non-Consumable",
                inventoryStatus: "LOWSTOCK",
                batches: [
                    {
                        batchId: 1201,
                        batchNumber: "Batch L12",
                        quantity: 69,
                        purchaseDate: "2024-04-03",
                        purchasePrice: 294.50537596623764,
                        unit: "Kg",
                        supplier: "Supplier L",
                        expDate: "2025-07-19",
                        status: "Inactive",
                        serialNumbers: [
                            { serialNumber: "SN121" },
                            { serialNumber: "SN122" },
                            { serialNumber: "SN123" },
                        ],
                    },
                ],
            },
            {
                id: 13,
                name: "Product M",
                brand: "Brand M",
                description: "Description M",
                category: "Non-Consumable",
                inventoryStatus: "INSTOCK",
                batches: [
                    {
                        batchId: 1301,
                        batchNumber: "Batch M13",
                        quantity: 64,
                        purchaseDate: "2024-01-25",
                        purchasePrice: 199.53306832872843,
                        unit: "L",
                        supplier: "Supplier M",
                        expDate: "2025-09-20",
                        status: "Active",
                        serialNumbers: [{ serialNumber: "SN131" }],
                    },
                ],
            },
            {
                id: 14,
                name: "Product N",
                brand: "Brand N",
                description: "Description N",
                category: "Non-Consumable",
                inventoryStatus: "OUTOFSTOCK",
                batches: [
                    {
                        batchId: 1401,
                        batchNumber: "Batch N14",
                        quantity: 55,
                        purchaseDate: "2024-05-04",
                        purchasePrice: 322.838180715147,
                        unit: "L",
                        supplier: "Supplier N",
                        expDate: "2025-10-15",
                        status: "Inactive",
                        serialNumbers: [
                            { serialNumber: "SN141" },
                            { serialNumber: "SN142" },
                            { serialNumber: "SN143" },
                            { serialNumber: "SN144" },
                        ],
                    },
                ],
            },
            {
                id: 15,
                name: "Product O",
                brand: "Brand O",
                description: "Description O",
                category: "Non-Consumable",
                inventoryStatus: "LOWSTOCK",
                batches: [
                    {
                        batchId: 1501,
                        batchNumber: "Batch O15",
                        quantity: 97,
                        purchaseDate: "2024-06-18",
                        purchasePrice: 437.6846365800603,
                        unit: "pcs",
                        supplier: "Supplier O",
                        expDate: "2025-09-19",
                        status: "Active",
                        serialNumbers: [
                            { serialNumber: "SN151" },
                            { serialNumber: "SN152" },
                            { serialNumber: "SN153" },
                            { serialNumber: "SN154" },
                        ],
                    },
                ],
            },
            {
                id: 16,
                name: "Product P",
                brand: "Brand P",
                description: "Description P",
                category: "Non-Consumable",
                inventoryStatus: "INSTOCK",
                batches: [
                    {
                        batchId: 1601,
                        batchNumber: "Batch P16",
                        quantity: 51,
                        purchaseDate: "2024-02-26",
                        purchasePrice: 54.292015984335144,
                        unit: "Kg",
                        supplier: "Supplier P",
                        expDate: "2025-04-02",
                        status: "Inactive",
                        serialNumbers: [
                            { serialNumber: "SN161" },
                            { serialNumber: "SN162" },
                            { serialNumber: "SN163" },
                        ],
                    },
                ],
            },
            {
                id: 17,
                name: "Product Q",
                brand: "Brand Q",
                description: "Description Q",
                category: "Non-Consumable",
                inventoryStatus: "OUTOFSTOCK",
                batches: [
                    {
                        batchId: 1701,
                        batchNumber: "Batch Q17",
                        quantity: 95,
                        purchaseDate: "2024-05-21",
                        purchasePrice: 362.94757139409927,
                        unit: "L",
                        supplier: "Supplier Q",
                        expDate: "2025-11-01",
                        status: "Inactive",
                        serialNumbers: [
                            { serialNumber: "SN171" },
                            { serialNumber: "SN172" },
                        ],
                    },
                ],
            },
            {
                id: 18,
                name: "Product R",
                brand: "Brand R",
                description: "Description R",
                category: "Non-Consumable",
                inventoryStatus: "INSTOCK",
                batches: [
                    {
                        batchId: 1801,
                        batchNumber: "Batch R18",
                        quantity: 32,
                        purchaseDate: "2024-02-16",
                        purchasePrice: 296.21780258727665,
                        unit: "Kg",
                        supplier: "Supplier R",
                        expDate: "2025-02-21",
                        status: "Active",
                        serialNumbers: [
                            { serialNumber: "SN181" },
                            { serialNumber: "SN182" },
                            { serialNumber: "SN183" },
                            { serialNumber: "SN184" },
                        ],
                    },
                ],
            },
            {
                id: 19,
                name: "Product S",
                brand: "Brand S",
                description: "Description S",
                category: "Non-Consumable",
                inventoryStatus: "INSTOCK",
                batches: [
                    {
                        batchId: 1901,
                        batchNumber: "Batch S19",
                        quantity: 69,
                        purchaseDate: "2024-11-22",
                        purchasePrice: 248.94770414131014,
                        unit: "Kg",
                        supplier: "Supplier S",
                        expDate: "2025-03-04",
                        status: "Inactive",
                        serialNumbers: [
                            { serialNumber: "SN191" },
                            { serialNumber: "SN192" },
                            { serialNumber: "SN193" },
                            { serialNumber: "SN194" },
                        ],
                    },
                ],
            },
            {
                id: 20,
                name: "Product T",
                brand: "Brand T",
                description: "Description T",
                category: "Non-Consumable",
                inventoryStatus: "INSTOCK",
                batches: [
                    {
                        batchId: 2001,
                        batchNumber: "Batch T20",
                        quantity: 72,
                        purchaseDate: "2024-10-12",
                        purchasePrice: 295.25933298279875,
                        unit: "L",
                        supplier: "Supplier T",
                        expDate: "2025-05-19",
                        status: "Inactive",
                        serialNumbers: [{ serialNumber: "SN201" }],
                    },
                ],
            },
        ];
    },

    getProductsMini() {
        return Promise.resolve(this.getProductsData().slice(0, 5));
    },

    getProductsSmall() {
        return Promise.resolve(this.getProductsData().slice(0, 10));
    },

    getProducts() {
        return Promise.resolve(this.getProductsData());
    },

    getProductsWithOrdersSmall() {
        return Promise.resolve(this.getProductsWithOrdersData().slice(0, 10));
    },

    getProductsWithOrders() {
        return Promise.resolve(this.getProductsWithOrdersData());
    },
};
