import { ref } from "vue";

export const rooms = ref([
    {
        id: 1,
        roomNumber: "101",
        floor: "1st Floor",
        image: "https://via.placeholder.com/300",
        name: "Room 101",
        type: "Double Size Bed",
        description: "Perfect for two guests with additional space.",
        status: "Available",
        rate: {
            "6 Hours": 50,
            "12 Hours": 80,
            "24 Hours": 120,
        },
        cleaningStatus: "Clean",
        guestDetails: {
            guestName: null,
            cellphone: null,
            selectedHours: null,
            checkIn: null,
            checkOut: null,
        },
    },
    {
        id: 2,
        roomNumber: "102",
        floor: "1st Floor",
        image: "https://via.placeholder.com/300",
        name: "Room 102",
        type: "Single Size Bed",
        description: "A cozy room for a single guest.",
        status: "Occupied",
        rate: {
            "6 Hours": 30,
            "12 Hours": 50,
            "24 Hours": 90,
        },
        cleaningStatus: "Clean",
        guestDetails: {
            guestName: "John Doe",
            cellphone: "123-456-7890",
            selectedHours: 24,
            checkIn: "2025-01-06 14:00",
            checkOut: "2025-01-07 14:00",
        },
    },
    {
        id: 3,
        roomNumber: "103",
        floor: "2nd Floor",
        image: "https://via.placeholder.com/300",
        name: "Room 103",
        type: "King Size Bed",
        description: "A luxurious suite for families or groups.",
        status: "Available",
        rate: {
            "6 Hours": 100,
            "12 Hours": 150,
            "24 Hours": 250,
        },
        cleaningStatus: "Needs Cleaning",
        guestDetails: {
            guestName: null,
            cellphone: null,
            selectedHours: null,
            checkIn: null,
            checkOut: null,
        },
    },
    {
        id: 4,
        roomNumber: "104",
        floor: "2nd Floor",
        image: "https://via.placeholder.com/300",
        name: "Room 104",
        type: "King Size Bed",
        description: "A luxurious suite for families or groups.",
        status: "Cleaning",
        rate: {
            "6 Hours": 100,
            "12 Hours": 150,
            "24 Hours": 250,
        },
        cleaningStatus: "Needs Cleaning",
        guestDetails: {
            guestName: null,
            cellphone: null,
            selectedHours: null,
            checkIn: null,
            checkOut: null,
        },
    },
    {
        id: 5,
        roomNumber: "105",
        floor: "2nd Floor",
        image: "https://via.placeholder.com/300",
        name: "Room 105",
        type: "Double Size Bed",
        description: "Spacious room perfect for couples.",
        status: "Booked",
        rate: {
            "6 Hours": 60,
            "12 Hours": 100,
            "24 Hours": 140,
        },
        cleaningStatus: "In Progress",
        guestDetails: {
            guestName: "Jane Smith",
            cellphone: "987-654-3210",
            selectedHours: 12,
            checkIn: "2025-01-06 10:00",
            checkOut: "2025-01-06 22:00",
        },
    },
]);
